/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Myclass */

#ifndef _Included_Myclass
#define _Included_Myclass
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
